server:
  port: 8080
spring:
  application:
    name: customer
  zipkin:
      base-url: http://localhost:9411
  datasource:
    username: amigoscode
    url: jdbc:postgresql://localhost:5432/customer
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
          ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enabled: true
